package com.animaconnected.watch.provider.demo;

/* compiled from: LocationDemoData.kt */
/* loaded from: classes3.dex */
public final class LocationDemoData {
    public static final LocationDemoData INSTANCE = new LocationDemoData();
    public static final String encodedRouteMalmo1 = "m|irIy_wnAa@i@?G?IBJ?E@@@DCECKAIESAMCSAOAWCSAQAMAKCQAKAI?I@K?K@I?IBKDODGBGDK@EDI@ADIBC@CBEDGBEBIBI@C?E@K?O?OAIAIACAKACCIAICK?CCGEICCACECAAGCAAG?A?I@EBA?GBEBEBGBCBGBK@KBKBG?GAGAECGCEEIEGEGEKGGCGCGCGEECECIGGGGAECGAGAGAE?EAE?ECGCECECECEAECEAGCGAE?IAGAG?G?KAE?EAGEEEEGGKCKCKCOCKAIAICKCICGEECEGAA?GBA@C@E@G?C@E?E@G@E@GBEBIBGBE@G?EAGAGAEAEAG?EAEAGCICEAECE?ECEEA?GECEEEEGCECEEKCGEIGGEEEEEEECGEEECCEAEAECEAIGCCECGEAAECEEGGGGEGCCEIAIACCK?CCK?CCOACAEEM?CAEAGAIAICGAIAICIACCI?ACGAEEIACCGCIAGCIAK?EAIAIAKACAGCGAACCCACCEC?ACCGGCMACCMAKCKAICICKCKEMCIAGAOAWAQAOAOCMAKCMCIAICGAIAIAGAM?CCMCGAACCCGGGAACGCICGGMCIAGCICKCICICKEOCWESEUEOCIGQCMCMEUAICKCS?MAOBMBIDEFADAF?D?D?BAB?DAD?D@D@FDDDDDFBDDDDDDDBFBD@D@D@FABEDG@EDGBGDIBGDIBEDIBCDC@ABC@AB?H?@@@@DBBBBF@D@BDJ?B@D?H@B?H@F?F@B?D@A?C??@@?@@@?B@F?B?D?@?D?D?FBJ?D@L@B@FBL@HBDBZBPBHDJDFDDFDD@DDJBDBDDDBDDDDDFDH@HBHBHBF@HBHBFDJBHBFBFBHBFDFDFDBDDFDFDFDDBDBFDDDBFBF@HBH@H?H@HDH@BBFBDF@BBD@F@@?B@D@D@D?FBFBFDFBNFHFFBHDFDFDFBFFDDFDDDFHDBDDBDDFDDDDDDDFDH@FBH?J?J@F?H?H?HAJABAL?BAH?F?J?N?B@J@H@HBHBHBHBFDJDDDDD@DBB@D@D@D@H@@?D@D?H@DBFBFBDBBDDDBDBFDJDL@JDFBHDHDFDFDFDDDBDBD@HBD@D@H@D?D?D@DADADAFAFCDAHEBA@AFC@ADCBADAFA@?D@D@BDDFBDBFBDDDBDDFBBBFBDDHBFFJBDDDBDBDDFBBBDDFBDDDBDDFBFBDBDBFDFBHBDBHBH@J@JBJBHBN@HBL@H@J@H?J@H?J@L?B?H@J?H@J?BCH?@EFABCFA@CJABAPAD?DAH?JAL?D?H?J?H?L?B@P@J?B@H?D@H?H@H?N?LAJ?J?H?J?LALEVEXARCPCTCRCLCFCJCHAHAB?BAB";

    private LocationDemoData() {
    }
}
