package com.animaconnected.watch.fitness;

import androidx.core.util.Preconditions;
import com.animaconnected.firebase.AnalyticsConstants;
import com.animaconnected.watch.fitness.FitnessDatabaseParser;
import java.util.List;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.LongSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import no.nordicsemi.android.dfu.DfuBaseService;

/* compiled from: FitnessDatabaseParser.kt */
/* loaded from: classes3.dex */
public final class FitnessDatabaseParser$FitnessData$$serializer implements GeneratedSerializer<FitnessDatabaseParser.FitnessData> {
    public static final FitnessDatabaseParser$FitnessData$$serializer INSTANCE;
    private static final /* synthetic */ PluginGeneratedSerialDescriptor descriptor;

    static {
        FitnessDatabaseParser$FitnessData$$serializer fitnessDatabaseParser$FitnessData$$serializer = new FitnessDatabaseParser$FitnessData$$serializer();
        INSTANCE = fitnessDatabaseParser$FitnessData$$serializer;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.animaconnected.watch.fitness.FitnessDatabaseParser.FitnessData", fitnessDatabaseParser$FitnessData$$serializer, 19);
        pluginGeneratedSerialDescriptor.addElement(AnalyticsConstants.KEY_VERSION, false);
        pluginGeneratedSerialDescriptor.addElement("startOfDay", false);
        pluginGeneratedSerialDescriptor.addElement("goals", false);
        pluginGeneratedSerialDescriptor.addElement("profile", true);
        pluginGeneratedSerialDescriptor.addElement("activityData", true);
        pluginGeneratedSerialDescriptor.addElement("heartrateData", true);
        pluginGeneratedSerialDescriptor.addElement("restingHeartrateData", true);
        pluginGeneratedSerialDescriptor.addElement("sleepData", true);
        pluginGeneratedSerialDescriptor.addElement("sleepHistoryData", true);
        pluginGeneratedSerialDescriptor.addElement("standData", true);
        pluginGeneratedSerialDescriptor.addElement("powerData", true);
        pluginGeneratedSerialDescriptor.addElement("stressData", true);
        pluginGeneratedSerialDescriptor.addElement("wristData", true);
        pluginGeneratedSerialDescriptor.addElement("speedCalibrationData", true);
        pluginGeneratedSerialDescriptor.addElement("fitnessIndexData", true);
        pluginGeneratedSerialDescriptor.addElement("exerciseData", true);
        pluginGeneratedSerialDescriptor.addElement("sessionData", true);
        pluginGeneratedSerialDescriptor.addElement("locationData", true);
        pluginGeneratedSerialDescriptor.addElement("sessions", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    private FitnessDatabaseParser$FitnessData$$serializer() {
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public KSerializer<?>[] childSerializers() {
        KSerializer<?>[] kSerializerArr;
        kSerializerArr = FitnessDatabaseParser.FitnessData.$childSerializers;
        return new KSerializer[]{IntSerializer.INSTANCE, LongSerializer.INSTANCE, BuiltinSerializersKt.getNullable(FitnessDatabaseParser$Goals$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(FitnessConfig$$serializer.INSTANCE), kSerializerArr[4], kSerializerArr[5], kSerializerArr[6], kSerializerArr[7], kSerializerArr[8], kSerializerArr[9], kSerializerArr[10], kSerializerArr[11], kSerializerArr[12], kSerializerArr[13], kSerializerArr[14], kSerializerArr[15], kSerializerArr[16], kSerializerArr[17], kSerializerArr[18]};
    }

    /* JADX WARN: Failed to find 'out' block for switch in B:4:0x003e. Please report as an issue. */
    @Override // kotlinx.serialization.DeserializationStrategy
    public FitnessDatabaseParser.FitnessData deserialize(Decoder decoder) {
        KSerializer[] kSerializerArr;
        List list;
        List list2;
        List list3;
        List list4;
        List list5;
        List list6;
        List list7;
        List list8;
        KSerializer[] kSerializerArr2;
        List list9;
        List list10;
        FitnessConfig fitnessConfig;
        List list11;
        FitnessDatabaseParser.Goals goals;
        List list12;
        List list13;
        List list14;
        List list15;
        List list16;
        List list17;
        List list18;
        List list19;
        FitnessConfig fitnessConfig2;
        int r7;
        List list20;
        List list21;
        List list22;
        int r2;
        List list23;
        List list24;
        List list25;
        int r72;
        List list26;
        int r73;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor descriptor2 = getDescriptor();
        CompositeDecoder beginStructure = decoder.beginStructure(descriptor2);
        kSerializerArr = FitnessDatabaseParser.FitnessData.$childSerializers;
        beginStructure.decodeSequentially();
        List list27 = null;
        List list28 = null;
        List list29 = null;
        List list30 = null;
        List list31 = null;
        List list32 = null;
        List list33 = null;
        List list34 = null;
        List list35 = null;
        List list36 = null;
        FitnessDatabaseParser.Goals goals2 = null;
        FitnessConfig fitnessConfig3 = null;
        List list37 = null;
        List list38 = null;
        List list39 = null;
        long j = 0;
        int r9 = 0;
        int r19 = 0;
        boolean z = true;
        List list40 = null;
        List list41 = null;
        while (z) {
            List list42 = list41;
            int decodeElementIndex = beginStructure.decodeElementIndex(descriptor2);
            switch (decodeElementIndex) {
                case -1:
                    list = list27;
                    list2 = list40;
                    list3 = list31;
                    list4 = list39;
                    list5 = list42;
                    list6 = list28;
                    list7 = list30;
                    list8 = list38;
                    kSerializerArr2 = kSerializerArr;
                    list9 = list37;
                    list10 = list35;
                    fitnessConfig = fitnessConfig3;
                    list11 = list34;
                    goals = goals2;
                    z = false;
                    goals2 = goals;
                    list34 = list11;
                    fitnessConfig3 = fitnessConfig;
                    list35 = list10;
                    list37 = list9;
                    list12 = list8;
                    list28 = list6;
                    list39 = list4;
                    list27 = list;
                    list41 = list5;
                    list30 = list7;
                    list31 = list3;
                    list40 = list2;
                    KSerializer[] kSerializerArr3 = kSerializerArr2;
                    list38 = list12;
                    kSerializerArr = kSerializerArr3;
                case 0:
                    list = list27;
                    list2 = list40;
                    list3 = list31;
                    list4 = list39;
                    list5 = list42;
                    list6 = list28;
                    list7 = list30;
                    list8 = list38;
                    kSerializerArr2 = kSerializerArr;
                    list9 = list37;
                    list10 = list35;
                    fitnessConfig = fitnessConfig3;
                    list11 = list34;
                    goals = goals2;
                    r9 |= 1;
                    r19 = beginStructure.decodeIntElement(descriptor2, 0);
                    goals2 = goals;
                    list34 = list11;
                    fitnessConfig3 = fitnessConfig;
                    list35 = list10;
                    list37 = list9;
                    list12 = list8;
                    list28 = list6;
                    list39 = list4;
                    list27 = list;
                    list41 = list5;
                    list30 = list7;
                    list31 = list3;
                    list40 = list2;
                    KSerializer[] kSerializerArr32 = kSerializerArr2;
                    list38 = list12;
                    kSerializerArr = kSerializerArr32;
                case 1:
                    list = list27;
                    list2 = list40;
                    list3 = list31;
                    list4 = list39;
                    list5 = list42;
                    list6 = list28;
                    list7 = list30;
                    list8 = list38;
                    kSerializerArr2 = kSerializerArr;
                    list9 = list37;
                    list10 = list35;
                    fitnessConfig = fitnessConfig3;
                    list11 = list34;
                    goals = goals2;
                    r9 |= 2;
                    j = beginStructure.decodeLongElement(descriptor2, 1);
                    goals2 = goals;
                    list34 = list11;
                    fitnessConfig3 = fitnessConfig;
                    list35 = list10;
                    list37 = list9;
                    list12 = list8;
                    list28 = list6;
                    list39 = list4;
                    list27 = list;
                    list41 = list5;
                    list30 = list7;
                    list31 = list3;
                    list40 = list2;
                    KSerializer[] kSerializerArr322 = kSerializerArr2;
                    list38 = list12;
                    kSerializerArr = kSerializerArr322;
                case 2:
                    list = list27;
                    list2 = list40;
                    list3 = list31;
                    list4 = list39;
                    list5 = list42;
                    list6 = list28;
                    list7 = list30;
                    list8 = list38;
                    kSerializerArr2 = kSerializerArr;
                    list9 = list37;
                    list10 = list35;
                    fitnessConfig = fitnessConfig3;
                    list11 = list34;
                    goals = (FitnessDatabaseParser.Goals) beginStructure.decodeNullableSerializableElement(descriptor2, 2, FitnessDatabaseParser$Goals$$serializer.INSTANCE, goals2);
                    r9 |= 4;
                    goals2 = goals;
                    list34 = list11;
                    fitnessConfig3 = fitnessConfig;
                    list35 = list10;
                    list37 = list9;
                    list12 = list8;
                    list28 = list6;
                    list39 = list4;
                    list27 = list;
                    list41 = list5;
                    list30 = list7;
                    list31 = list3;
                    list40 = list2;
                    KSerializer[] kSerializerArr3222 = kSerializerArr2;
                    list38 = list12;
                    kSerializerArr = kSerializerArr3222;
                case 3:
                    list = list27;
                    list2 = list40;
                    list13 = list31;
                    list14 = list39;
                    list15 = list42;
                    list16 = list28;
                    list17 = list38;
                    kSerializerArr2 = kSerializerArr;
                    list18 = list37;
                    list19 = list35;
                    fitnessConfig2 = (FitnessConfig) beginStructure.decodeNullableSerializableElement(descriptor2, 3, FitnessConfig$$serializer.INSTANCE, fitnessConfig3);
                    r7 = r9 | 8;
                    list20 = list30;
                    list21 = list36;
                    list31 = list13;
                    list22 = list18;
                    r2 = r7;
                    list23 = list15;
                    list24 = list14;
                    list25 = list17;
                    list28 = list16;
                    list39 = list24;
                    list5 = list23;
                    list3 = list31;
                    fitnessConfig3 = fitnessConfig2;
                    list35 = list19;
                    list7 = list20;
                    list37 = list22;
                    list36 = list21;
                    r9 = r2;
                    list12 = list25;
                    list27 = list;
                    list41 = list5;
                    list30 = list7;
                    list31 = list3;
                    list40 = list2;
                    KSerializer[] kSerializerArr32222 = kSerializerArr2;
                    list38 = list12;
                    kSerializerArr = kSerializerArr32222;
                case 4:
                    list = list27;
                    list2 = list40;
                    list13 = list31;
                    list14 = list39;
                    list15 = list42;
                    list16 = list28;
                    list17 = list38;
                    kSerializerArr2 = kSerializerArr;
                    list18 = (List) beginStructure.decodeSerializableElement(descriptor2, 4, kSerializerArr[4], list37);
                    r7 = r9 | 16;
                    list20 = list30;
                    list19 = list35;
                    list21 = list36;
                    fitnessConfig2 = fitnessConfig3;
                    list31 = list13;
                    list22 = list18;
                    r2 = r7;
                    list23 = list15;
                    list24 = list14;
                    list25 = list17;
                    list28 = list16;
                    list39 = list24;
                    list5 = list23;
                    list3 = list31;
                    fitnessConfig3 = fitnessConfig2;
                    list35 = list19;
                    list7 = list20;
                    list37 = list22;
                    list36 = list21;
                    r9 = r2;
                    list12 = list25;
                    list27 = list;
                    list41 = list5;
                    list30 = list7;
                    list31 = list3;
                    list40 = list2;
                    KSerializer[] kSerializerArr322222 = kSerializerArr2;
                    list38 = list12;
                    kSerializerArr = kSerializerArr322222;
                case 5:
                    list = list27;
                    list2 = list40;
                    list14 = list39;
                    list16 = list28;
                    list17 = (List) beginStructure.decodeSerializableElement(descriptor2, 5, kSerializerArr[5], list38);
                    kSerializerArr2 = kSerializerArr;
                    r2 = r9 | 32;
                    list20 = list30;
                    list21 = list36;
                    list22 = list37;
                    list31 = list31;
                    list23 = list42;
                    list19 = list35;
                    fitnessConfig2 = fitnessConfig3;
                    list24 = list14;
                    list25 = list17;
                    list28 = list16;
                    list39 = list24;
                    list5 = list23;
                    list3 = list31;
                    fitnessConfig3 = fitnessConfig2;
                    list35 = list19;
                    list7 = list20;
                    list37 = list22;
                    list36 = list21;
                    r9 = r2;
                    list12 = list25;
                    list27 = list;
                    list41 = list5;
                    list30 = list7;
                    list31 = list3;
                    list40 = list2;
                    KSerializer[] kSerializerArr3222222 = kSerializerArr2;
                    list38 = list12;
                    kSerializerArr = kSerializerArr3222222;
                case 6:
                    list2 = list40;
                    list = list27;
                    List list43 = (List) beginStructure.decodeSerializableElement(descriptor2, 6, kSerializerArr[6], list39);
                    int r74 = r9 | 64;
                    list20 = list30;
                    list21 = list36;
                    list22 = list37;
                    list31 = list31;
                    list19 = list35;
                    fitnessConfig2 = fitnessConfig3;
                    List list44 = list38;
                    kSerializerArr2 = kSerializerArr;
                    r2 = r74;
                    list23 = list42;
                    list24 = list43;
                    list25 = list44;
                    list39 = list24;
                    list5 = list23;
                    list3 = list31;
                    fitnessConfig3 = fitnessConfig2;
                    list35 = list19;
                    list7 = list20;
                    list37 = list22;
                    list36 = list21;
                    r9 = r2;
                    list12 = list25;
                    list27 = list;
                    list41 = list5;
                    list30 = list7;
                    list31 = list3;
                    list40 = list2;
                    KSerializer[] kSerializerArr32222222 = kSerializerArr2;
                    list38 = list12;
                    kSerializerArr = kSerializerArr32222222;
                case 7:
                    list2 = list40;
                    list23 = (List) beginStructure.decodeSerializableElement(descriptor2, 7, kSerializerArr[7], list42);
                    int r6 = r9 | 128;
                    list = list27;
                    list20 = list30;
                    list21 = list36;
                    list22 = list37;
                    list25 = list38;
                    list31 = list31;
                    kSerializerArr2 = kSerializerArr;
                    r2 = r6;
                    list19 = list35;
                    fitnessConfig2 = fitnessConfig3;
                    list24 = list39;
                    list39 = list24;
                    list5 = list23;
                    list3 = list31;
                    fitnessConfig3 = fitnessConfig2;
                    list35 = list19;
                    list7 = list20;
                    list37 = list22;
                    list36 = list21;
                    r9 = r2;
                    list12 = list25;
                    list27 = list;
                    list41 = list5;
                    list30 = list7;
                    list31 = list3;
                    list40 = list2;
                    KSerializer[] kSerializerArr322222222 = kSerializerArr2;
                    list38 = list12;
                    kSerializerArr = kSerializerArr322222222;
                case 8:
                    list20 = (List) beginStructure.decodeSerializableElement(descriptor2, 8, kSerializerArr[8], list30);
                    r72 = r9 | 256;
                    list = list27;
                    list2 = list40;
                    list21 = list36;
                    list22 = list37;
                    list25 = list38;
                    list24 = list39;
                    list31 = list31;
                    kSerializerArr2 = kSerializerArr;
                    r2 = r72;
                    list19 = list35;
                    fitnessConfig2 = fitnessConfig3;
                    list23 = list42;
                    list39 = list24;
                    list5 = list23;
                    list3 = list31;
                    fitnessConfig3 = fitnessConfig2;
                    list35 = list19;
                    list7 = list20;
                    list37 = list22;
                    list36 = list21;
                    r9 = r2;
                    list12 = list25;
                    list27 = list;
                    list41 = list5;
                    list30 = list7;
                    list31 = list3;
                    list40 = list2;
                    KSerializer[] kSerializerArr3222222222 = kSerializerArr2;
                    list38 = list12;
                    kSerializerArr = kSerializerArr3222222222;
                case 9:
                    list26 = list30;
                    list29 = (List) beginStructure.decodeSerializableElement(descriptor2, 9, kSerializerArr[9], list29);
                    r72 = r9 | DfuBaseService.ERROR_REMOTE_TYPE_SECURE;
                    list = list27;
                    list2 = list40;
                    list21 = list36;
                    list22 = list37;
                    list25 = list38;
                    list24 = list39;
                    list20 = list26;
                    kSerializerArr2 = kSerializerArr;
                    r2 = r72;
                    list19 = list35;
                    fitnessConfig2 = fitnessConfig3;
                    list23 = list42;
                    list39 = list24;
                    list5 = list23;
                    list3 = list31;
                    fitnessConfig3 = fitnessConfig2;
                    list35 = list19;
                    list7 = list20;
                    list37 = list22;
                    list36 = list21;
                    r9 = r2;
                    list12 = list25;
                    list27 = list;
                    list41 = list5;
                    list30 = list7;
                    list31 = list3;
                    list40 = list2;
                    KSerializer[] kSerializerArr32222222222 = kSerializerArr2;
                    list38 = list12;
                    kSerializerArr = kSerializerArr32222222222;
                case 10:
                    list26 = list30;
                    list28 = (List) beginStructure.decodeSerializableElement(descriptor2, 10, kSerializerArr[10], list28);
                    r72 = r9 | 1024;
                    list = list27;
                    list2 = list40;
                    list21 = list36;
                    list22 = list37;
                    list25 = list38;
                    list24 = list39;
                    list20 = list26;
                    kSerializerArr2 = kSerializerArr;
                    r2 = r72;
                    list19 = list35;
                    fitnessConfig2 = fitnessConfig3;
                    list23 = list42;
                    list39 = list24;
                    list5 = list23;
                    list3 = list31;
                    fitnessConfig3 = fitnessConfig2;
                    list35 = list19;
                    list7 = list20;
                    list37 = list22;
                    list36 = list21;
                    r9 = r2;
                    list12 = list25;
                    list27 = list;
                    list41 = list5;
                    list30 = list7;
                    list31 = list3;
                    list40 = list2;
                    KSerializer[] kSerializerArr322222222222 = kSerializerArr2;
                    list38 = list12;
                    kSerializerArr = kSerializerArr322222222222;
                case 11:
                    list26 = list30;
                    list32 = (List) beginStructure.decodeSerializableElement(descriptor2, 11, kSerializerArr[11], list32);
                    r72 = r9 | 2048;
                    list = list27;
                    list2 = list40;
                    list21 = list36;
                    list22 = list37;
                    list25 = list38;
                    list24 = list39;
                    list20 = list26;
                    kSerializerArr2 = kSerializerArr;
                    r2 = r72;
                    list19 = list35;
                    fitnessConfig2 = fitnessConfig3;
                    list23 = list42;
                    list39 = list24;
                    list5 = list23;
                    list3 = list31;
                    fitnessConfig3 = fitnessConfig2;
                    list35 = list19;
                    list7 = list20;
                    list37 = list22;
                    list36 = list21;
                    r9 = r2;
                    list12 = list25;
                    list27 = list;
                    list41 = list5;
                    list30 = list7;
                    list31 = list3;
                    list40 = list2;
                    KSerializer[] kSerializerArr3222222222222 = kSerializerArr2;
                    list38 = list12;
                    kSerializerArr = kSerializerArr3222222222222;
                case 12:
                    list26 = list30;
                    list33 = (List) beginStructure.decodeSerializableElement(descriptor2, 12, kSerializerArr[12], list33);
                    r72 = r9 | 4096;
                    list = list27;
                    list2 = list40;
                    list21 = list36;
                    list22 = list37;
                    list25 = list38;
                    list24 = list39;
                    list20 = list26;
                    kSerializerArr2 = kSerializerArr;
                    r2 = r72;
                    list19 = list35;
                    fitnessConfig2 = fitnessConfig3;
                    list23 = list42;
                    list39 = list24;
                    list5 = list23;
                    list3 = list31;
                    fitnessConfig3 = fitnessConfig2;
                    list35 = list19;
                    list7 = list20;
                    list37 = list22;
                    list36 = list21;
                    r9 = r2;
                    list12 = list25;
                    list27 = list;
                    list41 = list5;
                    list30 = list7;
                    list31 = list3;
                    list40 = list2;
                    KSerializer[] kSerializerArr32222222222222 = kSerializerArr2;
                    list38 = list12;
                    kSerializerArr = kSerializerArr32222222222222;
                case 13:
                    list26 = list30;
                    list31 = (List) beginStructure.decodeSerializableElement(descriptor2, 13, kSerializerArr[13], list31);
                    r72 = r9 | DfuBaseService.ERROR_REMOTE_MASK;
                    list = list27;
                    list2 = list40;
                    list21 = list36;
                    list22 = list37;
                    list25 = list38;
                    list24 = list39;
                    list20 = list26;
                    kSerializerArr2 = kSerializerArr;
                    r2 = r72;
                    list19 = list35;
                    fitnessConfig2 = fitnessConfig3;
                    list23 = list42;
                    list39 = list24;
                    list5 = list23;
                    list3 = list31;
                    fitnessConfig3 = fitnessConfig2;
                    list35 = list19;
                    list7 = list20;
                    list37 = list22;
                    list36 = list21;
                    r9 = r2;
                    list12 = list25;
                    list27 = list;
                    list41 = list5;
                    list30 = list7;
                    list31 = list3;
                    list40 = list2;
                    KSerializer[] kSerializerArr322222222222222 = kSerializerArr2;
                    list38 = list12;
                    kSerializerArr = kSerializerArr322222222222222;
                case 14:
                    list26 = list30;
                    list34 = (List) beginStructure.decodeSerializableElement(descriptor2, 14, kSerializerArr[14], list34);
                    r72 = r9 | DfuBaseService.ERROR_CONNECTION_MASK;
                    list = list27;
                    list2 = list40;
                    list21 = list36;
                    list22 = list37;
                    list25 = list38;
                    list24 = list39;
                    list20 = list26;
                    kSerializerArr2 = kSerializerArr;
                    r2 = r72;
                    list19 = list35;
                    fitnessConfig2 = fitnessConfig3;
                    list23 = list42;
                    list39 = list24;
                    list5 = list23;
                    list3 = list31;
                    fitnessConfig3 = fitnessConfig2;
                    list35 = list19;
                    list7 = list20;
                    list37 = list22;
                    list36 = list21;
                    r9 = r2;
                    list12 = list25;
                    list27 = list;
                    list41 = list5;
                    list30 = list7;
                    list31 = list3;
                    list40 = list2;
                    KSerializer[] kSerializerArr3222222222222222 = kSerializerArr2;
                    list38 = list12;
                    kSerializerArr = kSerializerArr3222222222222222;
                case 15:
                    list26 = list30;
                    list35 = (List) beginStructure.decodeSerializableElement(descriptor2, 15, kSerializerArr[15], list35);
                    r73 = DfuBaseService.ERROR_CONNECTION_STATE_MASK;
                    r72 = r73 | r9;
                    list = list27;
                    list2 = list40;
                    list21 = list36;
                    list22 = list37;
                    list25 = list38;
                    list24 = list39;
                    list20 = list26;
                    kSerializerArr2 = kSerializerArr;
                    r2 = r72;
                    list19 = list35;
                    fitnessConfig2 = fitnessConfig3;
                    list23 = list42;
                    list39 = list24;
                    list5 = list23;
                    list3 = list31;
                    fitnessConfig3 = fitnessConfig2;
                    list35 = list19;
                    list7 = list20;
                    list37 = list22;
                    list36 = list21;
                    r9 = r2;
                    list12 = list25;
                    list27 = list;
                    list41 = list5;
                    list30 = list7;
                    list31 = list3;
                    list40 = list2;
                    KSerializer[] kSerializerArr32222222222222222 = kSerializerArr2;
                    list38 = list12;
                    kSerializerArr = kSerializerArr32222222222222222;
                case 16:
                    list26 = list30;
                    list36 = (List) beginStructure.decodeSerializableElement(descriptor2, 16, kSerializerArr[16], list36);
                    r73 = 65536;
                    r72 = r73 | r9;
                    list = list27;
                    list2 = list40;
                    list21 = list36;
                    list22 = list37;
                    list25 = list38;
                    list24 = list39;
                    list20 = list26;
                    kSerializerArr2 = kSerializerArr;
                    r2 = r72;
                    list19 = list35;
                    fitnessConfig2 = fitnessConfig3;
                    list23 = list42;
                    list39 = list24;
                    list5 = list23;
                    list3 = list31;
                    fitnessConfig3 = fitnessConfig2;
                    list35 = list19;
                    list7 = list20;
                    list37 = list22;
                    list36 = list21;
                    r9 = r2;
                    list12 = list25;
                    list27 = list;
                    list41 = list5;
                    list30 = list7;
                    list31 = list3;
                    list40 = list2;
                    KSerializer[] kSerializerArr322222222222222222 = kSerializerArr2;
                    list38 = list12;
                    kSerializerArr = kSerializerArr322222222222222222;
                case 17:
                    list26 = list30;
                    list27 = (List) beginStructure.decodeSerializableElement(descriptor2, 17, kSerializerArr[17], list27);
                    r73 = 131072;
                    r72 = r73 | r9;
                    list = list27;
                    list2 = list40;
                    list21 = list36;
                    list22 = list37;
                    list25 = list38;
                    list24 = list39;
                    list20 = list26;
                    kSerializerArr2 = kSerializerArr;
                    r2 = r72;
                    list19 = list35;
                    fitnessConfig2 = fitnessConfig3;
                    list23 = list42;
                    list39 = list24;
                    list5 = list23;
                    list3 = list31;
                    fitnessConfig3 = fitnessConfig2;
                    list35 = list19;
                    list7 = list20;
                    list37 = list22;
                    list36 = list21;
                    r9 = r2;
                    list12 = list25;
                    list27 = list;
                    list41 = list5;
                    list30 = list7;
                    list31 = list3;
                    list40 = list2;
                    KSerializer[] kSerializerArr3222222222222222222 = kSerializerArr2;
                    list38 = list12;
                    kSerializerArr = kSerializerArr3222222222222222222;
                case 18:
                    list40 = (List) beginStructure.decodeSerializableElement(descriptor2, 18, kSerializerArr[18], list40);
                    r9 |= 262144;
                    list41 = list42;
                    list30 = list30;
                default:
                    throw new UnknownFieldException(decodeElementIndex);
            }
        }
        List list45 = list27;
        List list46 = list40;
        List list47 = list31;
        List list48 = list37;
        List list49 = list39;
        List list50 = list28;
        List list51 = list35;
        FitnessConfig fitnessConfig4 = fitnessConfig3;
        List list52 = list38;
        List list53 = list34;
        FitnessDatabaseParser.Goals goals3 = goals2;
        beginStructure.endStructure(descriptor2);
        return new FitnessDatabaseParser.FitnessData(r9, r19, j, goals3, fitnessConfig4, list48, list52, list49, list41, list30, list29, list50, list32, list33, list47, list53, list51, list36, list45, list46, (SerializationConstructorMarker) null);
    }

    @Override // kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public SerialDescriptor getDescriptor() {
        return descriptor;
    }

    @Override // kotlinx.serialization.SerializationStrategy
    public void serialize(Encoder encoder, FitnessDatabaseParser.FitnessData value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor descriptor2 = getDescriptor();
        CompositeEncoder beginStructure = encoder.beginStructure(descriptor2);
        FitnessDatabaseParser.FitnessData.write$Self$watch_release(value, beginStructure, descriptor2);
        beginStructure.endStructure(descriptor2);
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public KSerializer<?>[] typeParametersSerializers() {
        return Preconditions.EMPTY_SERIALIZER_ARRAY;
    }
}
